### ISSUE TITLE
Can't import glm model

### ISSUE THREAD

**Issue by spoilt-exile** [mrwonko/Blender-Jedi-Academy-Tools#8]
I've downloaded your addon but can't use it. I've tried import original glm modles from JA and in result I only got skeleton without model mesh. Here is error message from script:

Traceback (most recent call last):
  File "/storage/Софт и хлам/soft/BLENDER STABLE/2.71/scripts/addons/io_scene_ghoul2/mrw_g2_operators.py", line 84, in execute
    success, message = scene.saveToBlender(scale, skin, self.guessTextures, self.skeletonFixes)
  File "/storage/Софт и хлам/soft/BLENDER STABLE/2.71/scripts/addons/io_scene_ghoul2/mrw_g2_scene.py", line 127, in saveToBlender
    success, message = self.glm.saveToBlender(self.basepath, self.gla, scene_root, skin_rel, guessTextures)
  File "/storage/Софт и хлам/soft/BLENDER STABLE/2.71/scripts/addons/io_scene_ghoul2/mrw_g2_glm.py", line 1001, in saveToBlender
    self.LODCollection.saveToBlender(data)
  File "/storage/Софт и хлам/soft/BLENDER STABLE/2.71/scripts/addons/io_scene_ghoul2/mrw_g2_glm.py", line 825, in saveToBlender
    LOD.saveToBlender(data, root)
  File "/storage/Софт и хлам/soft/BLENDER STABLE/2.71/scripts/addons/io_scene_ghoul2/mrw_g2_glm.py", line 756, in saveToBlender
    obj = surface.saveToBlender(data, self.level)
  File "/storage/Софт и хлам/soft/BLENDER STABLE/2.71/scripts/addons/io_scene_ghoul2/mrw_g2_glm.py", line 593, in saveToBlender
    mesh.faces.add(self.numTriangles)
AttributeError: 'Mesh' object has no attribute 'faces'

location: <unknown location>:-1

OS: Debian Linux;
Blender 2.71
Python 2.7.7rc1

Please help.

**Comment by mrwonko** [comment]
It hasn't been tested with versions beyond 2.69, maybe it doesn't work on 2.71.

**Comment by spoilt-exile** [comment]
Thank you for quick replay. I've already replace mesh.faces with mesh.polygons like mentioned in 2.7x guidlines, but there is more errors with this script in 2.7, so I install 2.62 and it works for me.
